# fly.toml app configuration file generated for fly-log-shipper-jupptest on 2023-05-03T15:24:21Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fly-log-shipper-jupptest"
primary_region = "ams"

[build]
  image = "ghcr.io/superfly/fly-log-shipper:latest"

[metrics]
  path = "/metrics"
  port = 9598

[[services]]
  http_checks = []
  internal_port = 8686

